---
:concurrency: 5
:verbose: true
staging:
  concurrency: 10
production:
  concurrency: 20
  verbose: false
# Create two queues, defaut and high priority
# The 2 tells Sidekiq to check the associated queue twice as often
:queues:
  - default
  - mailers
  - [carts, 2]